import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>システム開発研究会</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/zcv4ykv.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='' />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,700,1,0" />
      </Head>

      <main className={styles.main}>
        <div className={styles.title}>
          <div>
            <p>THE SYSTEM DEVELOPMENT STUDY GROUP</p>
            <h1>奈良高専システム開発研究会</h1>
          </div>
        </div>

        <section className={styles.about}>
          <h1>ABOUT US</h1>
          <div>
            <div>
              <h2>システム開発研究会とは？</h2>
              <p>わたしたちは日々「システム創り」に挑戦しています。</p>
              <p>LEGO® を用いてWorld Robot Olympiad (WRO) へ出場したり、高専祭ではハンドベルの自動演奏機を製作するなど幅広く活動。</p>
              <p>チャレンジ精神を全力でサポートします。</p>
              <p>学年の垣根はなく、フラットな環境で「システム創り」に取り組めます。</p>
            </div>
            <div className={styles.info}>
              <hr />
              <div>
                {/* <span className="material-symbols-outlined">group</span> */}
                <h2>部員数</h2>
                <p>11人</p>
              </div>
              <hr />
              <div>
                <h2>活動日</h2>
                <p>放課後 (水曜日、金曜日) </p>
              </div>
              <hr />
              <div>
                <h2>活動場所</h2>
                <p>電子工学実験室</p>
              </div>
              <hr />
            </div>
          </div>
          <div className={styles.recommend}>
            <h2>入部歓迎！</h2>
            <div>
              <div>
                <p>経験がなくても大丈夫！</p>
              </div>
              <div>
                <p>先輩が優しくサポート！</p>
              </div>
              <div>
                <p>兼部可能！</p>
              </div>
            </div>
          </div>
        </section>

        {/* <div className={styles.recommend}>
          <p>こんにちは。これは例です。</p>
        </div> */}

        <section className={styles.works}>
          <h1>WORKS</h1>
          <div>
            <h2>LEGO®</h2>
            <div className={styles.video}>
              <iframe src="https://www.youtube.com/embed/jNQXAC9IVRw?controls=0&loop=1&playlist=jNQXAC9IVRw&rel=0&cc_load_policy=0" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" frameBorder={0}></iframe>
            </div>
          </div>
          <div>
            <h2>ハンドベル自動演奏機</h2>
            <div className={styles.video}>
              <iframe src="https://www.youtube.com/embed/jNQXAC9IVRw?controls=0&loop=1&playlist=jNQXAC9IVRw&rel=0&cc_load_policy=0" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" frameBorder={0}></iframe>
            </div>
          </div>
          <div>
            <h2>LEDキューブ</h2>
            <div className={styles.video}>
              <iframe src="https://www.youtube.com/embed/jNQXAC9IVRw?controls=0&loop=1&playlist=jNQXAC9IVRw&rel=0&cc_load_policy=0" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" frameBorder={0}></iframe>
            </div>
          </div>
          <div>
            <h2>LEDキューブ</h2>
            <div className={styles.video}>
              <iframe src="https://www.youtube.com/embed/jNQXAC9IVRw?controls=0&loop=1&playlist=jNQXAC9IVRw&rel=0&cc_load_policy=0" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" frameBorder={0}></iframe>
            </div>
          </div>
        </section>

        <section className={styles.faq}>
          <h1> FAQ</h1>
          <div>
            <h2>部員は何人ですか</h2>
            <p>一年生　人。ニ年生　人。三年生　人。四年生　人。計11人です。</p>
          </div>
          <div>
            <h2>活動日はいつですか</h2>
            <p>水曜日と金曜日の放課後です。</p>
          </div>
          <div>
            <h2>活動場所はどこですか</h2>
            <p>電子制御工学科棟4F、電子工学実験室です。</p>
          </div>
        </section>

        {/* <video src=""></video> */}

        {/* <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p> */}

        {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      <footer className={styles.footer}>
        <p>© システム開発研究会 All rIghts reserved.</p>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>
    </div >
  )
}

export default Home
